language: node_js

node_js:
  - '0.10'
  - '0.11'

before_install:
  - npm update -g npm

before_script:
- npm install -g istanbul
- npm install -g mocha

after_success:
  - shopt -s globstar
  - istanbul cover _mocha -- -R spec ./test/**/*.js && cat ./coverage/lcov.info| ./node_modules/coveralls/bin/coveralls.js

