language: node_js

env:
  CODECLIMATE_REPO_TOKEN: d7e9d1a6a7c11ec9e3e24586b95a9e39e0ff333eda8cc8da751e1889cb013aca

node_js:
  - '0.10'
  - '0.11'

before_install:
  - npm update -g npm

before_script:
- npm install -g istanbul
- npm install -g mocha
- npm install -g codeclimate-test-reporter

after_success:
  - shopt -s globstar
  - istanbul cover _mocha -- -R spec ./test/**/*.js
  - codeclimate < ./coverage/lcov.info
